### ISSUE TITLE
Feature: Add support for conditional slack notifications 

### ISSUE THREAD

**Issue by jjpatel361** [maasglobal/serverless-plugin-notification#6]
**Use case**

It would be great to add built-in support to conditionally send slack notifications. One use case is, send notification only for specific deploys Prod / QA and not dev or feature branches. 

**Suggested** 

```
custom:
  notification:
    deployer: /* Default deployer name*/
    slack:
      enabled: {{self:provider.stage}}
```  
`enabled`  flag is `true` we perform notification.

Since [sendNotification](https://github.com/maasglobal/serverless-plugin-notification/blob/8d79c2594f1f57eee9918c4809c3c91602a3544d/index.js#L67) is the sink of all promises might as well put it there. or skip the entire promise chaining.  

Also thanks for this plugin. 🙏
